# Generated by Django 3.2.4 on 2021-06-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaUnormal',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaUtrabajador',
            fields=[
                ('rut', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=30)),
                ('especialidad', models.CharField(max_length=30)),
                ('telefono', models.IntegerField(max_length=30)),
            ],
        ),
    ]
